### ISSUE TITLE
Resulting files of search.py differ when looping

### ISSUE THREAD

**Issue by iboeckma** [irgroup/gelic#1]
There are different query results when looping through the fieldnames.json instead of assigning the variables manually. 

Looping:
![loopingResult](https://user-images.githubusercontent.com/49275358/64082612-f29ca100-cd11-11e9-997a-81825edddac9.png)

Assigning manually:
![manualResult](https://user-images.githubusercontent.com/49275358/64082615-f4fefb00-cd11-11e9-972e-d2034ed000b6.png)

**Comment by phschaer** [comment]
Sorry, I can't reproduce this bug. Can you please add some more information on how to run into this error?

Can you please make a short step-by-step description of how to produce these results?

**Comment by iboeckma** [comment]
I was just making the files ready so you could look over them, but then I tested the bug a bit more and realised that in the original script 

`f.close()`

is executed before 

`os.system("trec_eval/trec_eval dnb-collection/dnb_rel.txt title_txt_de.txt > " + str(v) + ".csv”)`

In the new script I switched it for unknown reasons. After I switched the lines again, the numbers of the original “manual” and new “automatic” script are now the same.

So the bug was in the lines of this marked red box:
![Screenshot 2019-10-06 at 20 05 58](https://user-images.githubusercontent.com/49275358/66273539-202abc00-e875-11e9-8665-e0684f89929c.png)

If you want I can write down more and post the files so you can look over them yourself, but the problem should be solved now.
